apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy.cloud.kuly/app: api-server
  name: api-server
  namespace: kuly-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy.cloud.kuly/app: api-server
  template:
    metadata:
      labels:
        deploy.cloud.kuly/app: api-server
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: api-server
        ports:
        - containerPort: 12270
          name: rpc
        - containerPort: 8080
          name: http
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "12270"
        - name: CONTROL_PLANE_HOST
          value: control-plane
        - name: CONTROL_PLANE_PORT
          value: "12270"
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    deploy.cloud.kuly/app: api-server
  name: api-http
  namespace: kuly-platform
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 8080
      protocol: TCP
      targetPort: http
  selector:
    deploy.cloud.kuly/app: api-server
